---
version: 3

dependencies:
  galaxy: requirements.yml

images:
  base_image:
    name: docker.io/redhat/ubi9:9.6

additional_build_steps:
  # install necessary python packages
  prepend_base: |
    RUN dnf install -y python3-pip-21.3.1
    RUN pip install --upgrade pip==25.2
    RUN pip install wheel==0.45.1
    RUN pip install openstacksdk==4.5.0
    RUN pip install ansible==8.7.0
    RUN pip install ansible-runner==2.4.1
    RUN pip install ansible-inventory==0.6.4
    RUN pip install pywinrm==0.5.0

  # install yum packages
  prepend_final: |
    RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -o /etc/yum.repos.d/terraform.repo
    RUN dnf install -y terraform-1.12.2
    RUN dnf install -y packer-1.14.1
    RUN dnf install -y git-2.47.3
    RUN dnf install -y sudo-1.9.5p2
    RUN dnf install -y sshpass-1.09

  # install openstack client and final clean up 
  append_final: |
    # the openstack clients required version of requests conflicts with the containers system package. this is easier than fighting it.
    # the openstacksdk package in the normal environment is all that is necessary for the openstack galaxy collection.
    # this is here just in case
    RUN python3 -m venv /runner/venv
    RUN /runner/venv/bin/pip install --upgrade pip==25.2
    RUN /runner/venv/bin/pip install wheel==0.45.1
    RUN /runner/venv/bin/pip install python-openstackclient==8.0.0

    RUN dnf clean all
    RUN pip cache purge
    RUN /runner/venv/bin/pip cache purge

    LABEL org.opencontainers.image.source https://github.com/joe-7195/ee
