---
version: 3

dependencies:
  galaxy: requirements.yml

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi:9.5

additional_build_steps:
  prepend_base: |
    LABEL org.opencontainers.image.source https://github.com/joe-7195/ee
    RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -o /etc/yum.repos.d/terraform.repo
    RUN yum update -y
    RUN yum install -y git
    RUN yum install -y terraform
    RUN yum install -y packer
    RUN yum install -y sshpass
    RUN yum install -y sudo
    RUN yum install -y python3-pip
    RUN yum clean all
    RUN pip install --upgrade pip
    RUN pip install wheel
    RUN pip install ansible-runner
    RUN pip install ansible-inventory 
    RUN pip install ansible
    RUN pip install pywinrm    