---
collections:
  - name: cloud.terraform
    version: ==4.0.0
  - name: openstack.cloud
    version: ==2.4.1
  - name: community.general
    version: ==11.2.1
  - name: community.docker
    version: ==4.7.0
  - name: community.mysql
    version: ==3.15.0
  - name: community.windows
    version: ==3.0.1
  - name: ansible.posix
    version: ==2.1.0
  - name: chocolatey.chocolatey
    version: ==1.5.3